name: streamlit_app_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - numpy
  - opencv
  - pillow
  - scipy
  - pip:
      - streamlit
      - torchmetrics
