_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
                - 55
            "4": 3.10.17
            "5": 0.20.0
            "8":
                - 3
            "12": 0.20.0
            "13": windows-amd64
architecture:
    value: ResNet18
batch_size:
    value: 32
dataset:
    value: Breast Thermal Images
epochs:
    value: 10
learning_rate:
    value: 0.0001
optimizer:
    value: Adam
